# Generated by Django 5.0.6 on 2024-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subwayNm', models.CharField(max_length=50)),
                ('trainNo', models.CharField(max_length=50)),
                ('statnNm', models.CharField(max_length=50)),
                ('statnTnm', models.CharField(max_length=50)),
                ('trainSttus', models.CharField(max_length=50)),
                ('updnLine', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
    ]
