# Generated by Django 5.0.6 on 2024-07-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindata',
            old_name='location',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='traindata',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='traindata',
            name='train_id',
        ),
        migrations.AddField(
            model_name='traindata',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='statnNm',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='statnTnm',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='subwayNm',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='trainNo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='trainSttus',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traindata',
            name='updnLine',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
